/* web 'planparam' */
declare @WEB_MEDECINS_ID int
set	@WEB_MEDECINS_ID=1201

SELECT 
 PL_PARAM.PL_PARAM_ID,PL_PARAM.NOM,
 (case when isnull(DEBUT_TRANCHE, 0) = 0 then '00:00' else ( Substring(Cast(PL_PARAM.DEBUT_TRANCHE  as varchar)
	,1
	,len(PL_PARAM.DEBUT_TRANCHE )-2) + ':' + Substring(Cast(PL_PARAM.DEBUT_TRANCHE as varchar)
	,len(PL_PARAM.DEBUT_TRANCHE )-1
	,len(PL_PARAM.DEBUT_TRANCHE )) ) end) BEG
 ,PL_PARAM.DEBUT_TRANCHE,
 (case when isnull(FIN_TRANCHE, 0) = 0  then '00:00' else ( Substring(Cast(PL_PARAM.FIN_TRANCHE  as varchar), 1
	,len(PL_PARAM.FIN_TRANCHE )-2) + ':' + Substring(Cast(PL_PARAM.FIN_TRANCHE as varchar)
	,len(PL_PARAM.FIN_TRANCHE )-1
	,len(PL_PARAM.FIN_TRANCHE )) ) end) FIN
 ,PL_PARAM.FIN_TRANCHE,FM_ORG.CODE,PL_PARAM.DUREE_TRANCHE,PL_PARAM.SHOW_WORKDAYS,PL_PARAM.SHOW_PLACE,
 PL_PARAM.TUNE_MANUAL,PL_PARAM.FM_INTORG_ID,PL_PARAM.ARCHIVE,PL_PARAM.TITLE_VERTICAL,PL_PARAM.TITLE_MINWIDTH,
 PL_PARAM.TITLE_HEIGHT,MED_PLPARAM.MEDECINS_ID
FROM
 PL_PARAM PL_PARAM 
LEFT OUTER JOIN FM_ORG FM_ORG ON FM_ORG.FM_ORG_ID = PL_PARAM.FM_INTORG_ID 
 JOIN MED_PLPARAM MED_PLPARAM ON PL_PARAM.PL_PARAM_ID = MED_PLPARAM.PL_PARAM_ID 
WHERE
 (MED_PLPARAM.MEDECINS_ID=(@WEB_MEDECINS_ID)) and
 (PL_PARAM.ARCHIVE not in (1)) 
order by nom
