select 
PL_SUBJ.PL_SUBJ_ID
,PL_SUBJ.NAME
,PL_SUBJ.*
,PL_EXAM.NAME
,PL_AGEND.*
from PL_SUBJ_PARAM 
inner join PL_SUBJ on PL_SUBJ_PARAM.PL_SUBJ_ID=PL_SUBJ.PL_SUBJ_ID
inner join PL_EXAM on PL_EXAM.PL_EXAM_ID=PL_SUBJ.PL_EXAM_ID
inner join PL_AGEND on PL_AGEND.PL_AGEND_ID=PL_SUBJ.PL_AGEND_ID1
where 
PL_PARAM_ID in(25) 
and(PL_SUBJ.ARCHIVE not in (1)) 
order by PL_SUBJ.NAME
