select PL_DAY_ID, PL_DAY.NAME DAY_NAME
	, PL_SUBJ.PL_SUBJ_ID, PL_SUBJ.NAME SUBJ_NAME
	, PL_PARAM.PL_PARAM_ID DEP_ID, PL_PARAM.NOM DEP_NAME
	, FM_ORG.LABEL ORG_NAME
from PL_DAY
 inner join PL_SUBJ on PL_SUBJ.pl_agend_id1=PL_DAY.pl_agend_id 
 inner join PL_SUBJ_PARAM on PL_SUBJ_PARAM.PL_SUBJ_ID=PL_SUBJ.PL_SUBJ_ID 
 inner join PL_PARAM PL_PARAM ON PL_PARAM.PL_PARAM_ID=PL_SUBJ_PARAM.PL_PARAM_ID 
 inner JOIN FM_ORG FM_ORG ON FM_ORG.FM_ORG_ID = PL_PARAM.FM_INTORG_ID 
where PL_DAY.PL_DAY_ID in (12226) 