declare @PL_AGEND_ID int
set	@PL_AGEND_ID=292

SELECT 
 min(START_TIME) MinTime,  max(END_TIME) MaxTime
FROM
 PL_DAY 
WHERE
PL_AGEND_ID in (@PL_AGEND_ID)


/* TfAgenda.dbrDays */
SELECT 
 pl_day.*
FROM
 pl_day 
WHERE
 PL_DAY.ENABLED=(1)
 and pl_agend_id in (@PL_AGEND_ID)
ORDER BY
 day_order


/* TfAgenda.dbrQuery1 */
SELECT 
 PL_INT.INT_FROM,PL_INT.INT_TO,PL_DAY.ENABLED,PL_LEG.COLOR,PL_LEG.FONT,
 PL_LEG.NAME,PL_DAY.DAY_ORDER,PL_INT.PL_INT_ID,PL_DAY.PL_DAY_ID,PL_DAY.DAY_OF_MONTH,
 PL_DAY.DAY_MONTH,PL_DAY.DAY_YEAR,PL_DAY.period_from,PL_DAY.period_to
FROM
 PL_INT PL_INT 
 JOIN PL_DAY PL_DAY ON PL_DAY.PL_DAY_ID = PL_INT.PL_DAY_ID 
 JOIN PL_LEG PL_LEG ON PL_LEG.PL_LEG_ID = PL_INT.PL_LEG_ID 
WHERE
 PL_DAY.ENABLED=(1)
 AND PL_AGEND_ID=(@PL_AGEND_ID)
ORDER BY DAY_ORDER

