select PL_SUBJ.PL_SUBJ_ID, PL_SUBJ.NAME,PL_PARAM.NOM,FM_ORG.LABEL
from PL_SUBJ 
inner join PL_SUBJ_PARAM on PL_SUBJ_PARAM.PL_SUBJ_ID=PL_SUBJ.PL_SUBJ_ID 
inner join PL_PARAM PL_PARAM ON PL_PARAM.PL_PARAM_ID=PL_SUBJ_PARAM.PL_PARAM_ID
inner JOIN FM_ORG FM_ORG ON FM_ORG.FM_ORG_ID = PL_PARAM.FM_INTORG_ID 
	where PL_SUBJ.PL_SUBJ_ID in(83) 
	and(PL_SUBJ.ARCHIVE not in (1)) 
	order by NAME