use medialog71

declare @PL_DAY_ID int
set	@PL_DAY_ID=18384

SELECT
 PL_INT.INT_FROM,PL_INT.INT_TO,PL_LEG.COLOR,PL_LEG.FONT
,PL_LEG.NAME
,PL_INT.PL_INT_ID
,PL_INT.PL_LEG_ID
,'#'
,PL_int.*
,PL_LEG.*
FROM
 PL_INT PL_INT 
 JOIN PL_LEG PL_LEG ON PL_LEG.PL_LEG_ID = PL_INT.PL_LEG_ID 
WHERE
PL_INT.PL_DAY_ID in (@PL_DAY_ID)
