SELECT 
 PLANNING.PLANNING_ID,PLANNING.PL_SUBJ_ID,PLANNING.DATE_CONS,PLANNING.HEURE,PLANNING.DUREE,PLANNING.PATIENTS_ID
,PLANNING.COLOR,PLANNING.FONT,PLANNING.DUREE_TEXT,PLANNING.PATIENT_ARRIVEE,PLANNING.PL_GENER_ID
,PLANNING.PL_EXAM_ID,PL_EXAM.NAME PL_EXAM_NAME
FROM
 PLANNING PLANNING 
 LEFT OUTER JOIN PL_EXAM PL_EXAM ON PL_EXAM.PL_EXAM_ID = PLANNING.PL_EXAM_ID 
WHERE
 --(PLANNING.PL_SUBJ_ID=326)
(PLANNING.DATE_CONS>=DATEADD(day, DATEDIFF(day, 0, getdate()), 0) AND PLANNING.DATE_CONS<=getdate())
 AND ((PLANNING.CANCELLED IS NULL) OR (PLANNING.CANCELLED=0))
 and ((PLANNING.STATUS IS NULL) OR (PLANNING.STATUS = 0))