SELECT 
PL_EXAM.PL_EXAM_ID
,PL_EXAM.NAME
,PL_EXAM.DUREE
,PL_EXAM.COLOR
,'|' '|'
,PL_SUBJ_EXAM.*
,'|' '|'
,PL_EXAM.*


FROM
 PL_EXAM 
 LEFT OUTER JOIN PL_SUBJ_EXAM ON PL_SUBJ_EXAM.PL_EXAM_ID = PL_EXAM.PL_EXAM_ID 
WHERE
PL_SUBJ_ID=326
order by PL_SUBJ_EXAM.EXAM_ORDER
