
update DM_SERVPRICE
set DM_SERVPRICE.DM_SERVPRICE_NORM_ID=DM_SERVPRICE.DM_SERVPRICE_ID
where DM_SERVPRICE.is_fact='n'
and  DM_SERVPRICE.DM_SERVPRICE_NORM_ID IS NULL

update DM_SERV_MEDS
set DM_SERV_MEDS.DM_SERV_MEDS_NORM_ID=DM_SERV_MEDS.DM_SERV_MEDS_ID
from DM_SERV_MEDS
join DM_SERVPRICE on DM_SERV_MEDS.DM_SERVPRICE_ID=DM_SERVPRICE.DM_SERVPRICE_ID
where DM_SERVPRICE.is_fact='n'
and  DM_SERV_MEDS.DM_SERV_MEDS_NORM_ID IS NULL


--select DM_SERV_MEDS.*
update DM_SERV_MEDS set IS_ACTIVE=1
from DM_SERV_MEDS
join DM_SERVPRICE on DM_SERV_MEDS.DM_SERVPRICE_ID=DM_SERVPRICE.DM_SERVPRICE_ID
where DM_SERVPRICE.is_fact='n'
--and  DM_SERV_MEDS.DM_SERV_MEDS_NORM_ID IS NULL