DECLARE @DBNAME as VARCHAR(20);
SET @DBNAME = 'medialog7';
--BACKUP LOG @DBNAME WITH NO_LOG;
--DBCC SHRINKDATABASE (@DBNAME,1,TRUNCATEONLY);

--DBCC SHRINKFILE (N'MEDIALOG_Log' , 5000)

--shrink database, leave 2% free space
--DBCC SHRINKDATABASE(@DBNAME, 2 )