

select DM_MEASURE.DM_MEASURE_ID, DM_MEASURE.LABEL from DM_MEASURE_PACKING 
       join DM_MEASURE on DM_MEASURE.DM_MEASURE_ID = DM_MEASURE_PACKING.DM_MEASURE_ID
where DM_PACK_RELEASE_ID = 6
order by DM_MEASURE_PACKING_ID



SELECT TOP 50
PR_DRUGS.FULL_NAME
,A_MEAS.DM_MEASURE_ID
,A_MEAS.FULL_NAME
,P_MEAS.DM_MEASURE_ID
,P_MEAS.FULL_NAME
,pm.DM_PACK_RELEASE_ID
,pm.LABEL

FROM
 PR_DRUGS
 LEFT OUTER JOIN DM_MEASURE A_MEAS ON A_MEAS.DM_MEASURE_ID = PR_DRUGS.ACTIVE_MEASURE_ID 
 LEFT OUTER JOIN DM_MEASURE P_MEAS ON P_MEAS.DM_MEASURE_ID = PR_DRUGS.PACKING_MEASURE_ID 
 left join DM_PACK_RELEASE pm on PR_DRUGS.DM_PACK_RELEASE_ID=pm.DM_PACK_RELEASE_ID
where PR_DRUGS.CODE like 'דולחאנ%'
 
