/* TDBData.<no name> 'bill' */
SELECT TOP 50000
--FM_BILLDET.FM_ORG1_id, 
--FM_CONTR.FM_ORG1_ID FM_CONTR_FM_ORG1_ID,
--FM_BILLDET_PAY.fm_org_id FM_BILLDET_PAY_fm_org_id,
--FM_BILLDET.FM_CLINK_PROG_ID,
--(case when (FM_CONTR.DEPOSIT=1) and (FM_SERV.SERV_TYPE='Z') then 100 else FM_BILLDET.ORG1_PERC end) ORG1_PERC_T,
 FM_BILL.BILL_DATE,FM_BILL.FM_BILL_ID
--,FM_DEP.LABEL
,FM_BILLDET.CNT,
 FM_BILL.PATIENTS_ID,FM_BILL.MEDECINS1_ID,FM_BILL.FM_DEP_ID
-- ,FM_BILL.DATE_CREATE
--,MEDECINS.NOM
--,FM_BILL.MEDECINS_CREATE_ID
,PATIENTS.NOM PATIENTS_NOM
--,FM_PRICETYPE.FM_PRICETYPE_ID
--,FM_PRICETYPE.CODE FM_PRICETYPE_CODE
,FM_BILLDET.FM_SERV_ID
,FM_BILLDET.PRICE

--,FM_SERVPRICE.PRICE FM_SERVPRICE_PRICE
,(select top 1 FM_SERVPRICE.PRICE
from FM_SERVPRICE
where 
FM_SERVPRICE.FM_SERV_ID=FM_BILLDET.FM_SERV_ID and FM_SERVPRICE.FM_PRICETYPE_ID=FM_BILLDET.FM_PRICETYPE_ID
and FM_SERVPRICE.DATE_FROM < DATEADD(day, DATEDIFF(day, 0, FM_BILLDET.DATE_CREATE), 0) 
order by FM_SERVPRICE_ID desc
) right_price
,FM_BILLDET.PRICE_TO_PAY
FROM FM_BILLDET FM_BILLDET
/* left outer JOIN FM_SERVPRICE on 
(FM_SERVPRICE.FM_SERV_ID=FM_BILLDET.FM_SERV_ID and FM_SERVPRICE.FM_PRICETYPE_ID=FM_BILLDET.FM_PRICETYPE_ID
and FM_SERVPRICE.DATE_FROM > DATEADD(day, DATEDIFF(day, 0, FM_BILLDET.DATE_CREATE), 0) 
)*/
 inner join FM_PRICETYPE on FM_PRICETYPE.FM_PRICETYPE_ID=FM_BILLDET.FM_PRICETYPE_ID
 LEFT OUTER JOIN FM_BILL FM_BILL ON FM_BILL.FM_BILL_ID = FM_BILLDET.FM_BILL_ID
 LEFT OUTER JOIN PATIENTS PATIENTS ON PATIENTS.PATIENTS_ID = FM_BILL.PATIENTS_ID 
 LEFT OUTER JOIN MEDECINS MEDECINS_1 ON MEDECINS_1.MEDECINS_ID = FM_BILL.MEDECINS1_ID 
 LEFT OUTER JOIN FM_DEP FM_DEP ON FM_DEP.FM_DEP_ID = FM_BILL.FM_DEP_ID 
 LEFT OUTER JOIN FM_PATIENTS FM_PATIENTS ON FM_BILL.FM_BILL_ID = FM_PATIENTS.FM_BILL_ID 
 LEFT OUTER JOIN MEDECINS MEDECINS ON MEDECINS.MEDECINS_ID = FM_BILL.MEDECINS_CREATE_ID 
LEFT OUTER JOIN FM_CLINK FM_CLINK ON FM_CLINK.FM_CLINK_ID = FM_BILLDET.FM_CLINK_ID 
LEFT OUTER JOIN FM_CONTR FM_CONTR ON FM_CONTR.FM_CONTR_ID = FM_CLINK.FM_CONTR_ID 
LEFT OUTER JOIN FM_ORG FM_ORG ON FM_ORG.FM_ORG_ID = FM_CONTR.FM_ORG1_ID
inner join FM_BILLDET_PAY on (FM_BILLDET_PAY.FM_BILLDET_ID=FM_BILLDET.FM_BILLDET_ID/* and FM_BILLDET_PAY.fm_org_id is not null*/) 
WHERE
 ((FM_BILL.BILL_DATE >= '20110101 00:00:00.000') and (FM_BILL.BILL_DATE < '20110201 00:00:00.000'))
AND (FM_BILL.MEDECINS1_ID in (361))
--and (FM_BILLDET.FM_ORG1_id is null)
ORDER BY
 FM_BILL.FM_BILL_ID DESC 
