SELECT 
SUM(FM_BILLDET.CNT) CNT
,SUM(case when FM_CLINK.FM_CONTR_ID in (9082) then FM_BILLDET.CNT else 0  end) CNT_GASO
,SUM(case when FM_CLINK.FM_CONTR_ID in (554) then FM_BILLDET.CNT else 0  end) CNT_OMS,
 SUM(case when FM_BILLDET_PAY.FM_ORG_ID is not null and FM_CLINK.FM_CONTR_ID not in (554, 9082) then FM_BILLDET.CNT  else 0  end) CNT_DMS
,SUM(case when FM_BILLDET_PAY.FM_ORG_ID is null then FM_BILLDET.CNT  else 0  end) CNT_PU
,COUNT(distinct FM_BILLDET.PATIENTS_ID) PAT_CNT
,COUNT(distinct case when FM_CLINK.FM_CONTR_ID in (9082) then FM_BILLDET.PATIENTS_ID else null  end) PAT_GASO
,COUNT(distinct case when FM_CLINK.FM_CONTR_ID in (554) then FM_BILLDET.PATIENTS_ID else null  end) PAT_OMS
,COUNT(distinct case when FM_BILLDET_PAY.FM_ORG_ID is not null and FM_CLINK.FM_CONTR_ID not in (554, 9082) then FM_BILLDET.PATIENTS_ID else null  end) PAT_DMS
,COUNT(distinct case when FM_BILLDET_PAY.FM_ORG_ID is null then FM_BILLDET.PATIENTS_ID else null  end) PAT_PU
,SUM(FM_BILLDET.PRICE_TO_PAY) PRICE_TO_PAY
,SUM(case when FM_CLINK.FM_CONTR_ID in (9082) then FM_BILLDET.PRICE_TO_PAY else 0  end) PAY_GASO
,SUM(case when FM_CLINK.FM_CONTR_ID in (554) then FM_BILLDET.PRICE_TO_PAY else 0  end) PAY_OMS,
 SUM(case when FM_BILLDET_PAY.FM_ORG_ID is not null and FM_CLINK.FM_CONTR_ID not in (554, 9082) then FM_BILLDET_PAY.PRICE else 0  end) PAY_DMS
,SUM(case when FM_BILLDET_PAY.FM_ORG_ID is null then FM_BILLDET_PAY.PRICE else 0  end) PAY_PU
FROM
 FM_BILLDET FM_BILLDET 
 LEFT OUTER JOIN FM_BILL FM_BILL ON FM_BILL.FM_BILL_ID = FM_BILLDET.FM_BILL_ID 
 LEFT OUTER JOIN FM_CLINK FM_CLINK ON FM_CLINK.FM_CLINK_ID = FM_BILLDET.FM_CLINK_ID
 JOIN FM_BILLDET_PAY FM_BILLDET_PAY ON FM_BILLDET.FM_BILLDET_ID = FM_BILLDET_PAY.FM_BILLDET_ID 
WHERE
 FM_BILL.BILL_DATE=DATEADD(day, DATEDIFF(day, 0, getdate()), 0)
