
select
z.*,
cim10.code
,isnull(CP_PLAN.PLAN_NAME,'')
from z_diag z
LEFT OUTER JOIN CIM10 CIM10 ON CIM10.Code=z.code
left JOIN CP_PLAN_CIM10 CP_PLAN_CIM10 ON CIM10.CIM10_ID = CP_PLAN_CIM10.CIM10_ID
left join CP_PLAN CP_PLAN on CP_PLAN.CP_PLAN_ID = CP_PLAN_CIM10.CP_PLAN_ID
--where PLAN_NAME is null
order by price desc

/*
SELECT DISTINCT TOP 1000
substring (CP_PLAN.PLAN_NAME,1,10) as стандарт--,  CIM10.CODE диагноз, CIM10.DESCRIPTION
FROM
 CP_PLAN CP_PLAN 
 JOIN CP_PLAN_CIM10 CP_PLAN_CIM10 ON CP_PLAN.CP_PLAN_ID = CP_PLAN_CIM10.CP_PLAN_ID 
 LEFT OUTER JOIN CIM10 CIM10 ON CIM10.CIM10_ID = CP_PLAN_CIM10.CIM10_ID 
 where plan_cost>0 and  PLAN_NAME like '%мэс%'
 order by стандарт--CIM10.CODE
 */
 /*
 SELECT DISTINCT TOP 1000
 CIM10.CODE диагноз, CIM10.DESCRIPTION
FROM
 CP_PLAN CP_PLAN 
 JOIN CP_PLAN_CIM10 CP_PLAN_CIM10 ON CP_PLAN.CP_PLAN_ID = CP_PLAN_CIM10.CP_PLAN_ID 
 LEFT OUTER JOIN CIM10 CIM10 ON CIM10.CIM10_ID = CP_PLAN_CIM10.CIM10_ID 
 where plan_cost>0 and  PLAN_NAME like '%мэс%'
 order by CIM10.CODE
 */