/*
SELECT top 1 * 
FROM DATA_HOSPITALIZ_ADM_ROOM
join MOTCONSU on MOTCONSU.MOTCONSU_ID=DATA_HOSPITALIZ_ADM_ROOM.MOTCONSU_ID
WHERE MODELS_ID=357 and
MOTCONSU.MOTCONSU_EV_ID=14819
*/

/*

IF(SUBSTR(
QUERY('{QUERY_1}','DIAGNOZ','DATA_DIAGNOSIS','MOTCONSU_ID=(select top 1 MOTCONSU_ID from MOTCONSU where MOTCONSU_EV_ID='+NUMSTR({=Текущее событие})+' and MODELS_ID=658 order by MOTCONSU_ID  desc) and VID_ZABOLEVANIQ=0'),1,1)=''
,'', QUERY('{QUERY_1}','DIAGNOZ','DATA_DIAGNOSIS','MOTCONSU_ID=(select top 1 MOTCONSU_ID from MOTCONSU where MOTCONSU_EV_ID='+NUMSTR({=Текущее событие})+' and MODELS_ID=658 order by MOTCONSU_ID  desc) and VID_ZABOLEVANIQ=0')+char(13)+char(10))+
IF(SUBSTR(
QUERY('{QUERY_1}','DIAGNOZ','DATA_DIAGNOSIS','MOTCONSU_ID=(select top 1 MOTCONSU_ID from MOTCONSU where MOTCONSU_EV_ID='+NUMSTR({=Текущее событие})+' and MODELS_ID=658 order by MOTCONSU_ID  desc) and VID_ZABOLEVANIQ=1'),1,1)=''
,'','Осложнение основного заболевания: '+ QUERY('{QUERY_1}','DIAGNOZ_PRI_VYPISKE','DATA_DIAGNOSIS','MOTCONSU_ID=(select top 1 MOTCONSU_ID from MOTCONSU where MOTCONSU_EV_ID='+NUMSTR({=Текущее событие})+' and MODELS_ID=658 order by MOTCONSU_ID  desc) and VID_ZABOLEVANIQ=1')+char(13)+char(10))+
IF(SUBSTR(
QUERY('{QUERY_1}','DIAGNOZ','DATA_DIAGNOSIS','MOTCONSU_ID=(select top 1 MOTCONSU_ID from MOTCONSU where MOTCONSU_EV_ID='+NUMSTR({=Текущее событие})+' and MODELS_ID=658 order by MOTCONSU_ID  desc) and VID_ZABOLEVANIQ=2'),1,1)=''
,'','Сопутствующее заболевание: '+ QUERY('{QUERY_1}','DIAGNOZ_PRI_VYPISKE','DATA_DIAGNOSIS','MOTCONSU_ID=(select top 1 MOTCONSU_ID from MOTCONSU where MOTCONSU_EV_ID='+NUMSTR({=Текущее событие})+' and MODELS_ID=658 order by MOTCONSU_ID  desc) and VID_ZABOLEVANIQ=2'))


*/
DECLARE @CRITERIA  AS VARCHAR(max)
DECLARE @sql AS VARCHAR(max)

SELECT top 1 cast(DIAGNOZ as varchar(max))+char(13)+char(10) as DIAGNOZ FROM  DATA_DIAGNOSIS data
join MOTCONSU on MOTCONSU.MOTCONSU_ID=DATA.MOTCONSU_ID 
WHERE MODELS_ID=658 and VID_ZABOLEVANIQ=0 and
MOTCONSU.MOTCONSU_EV_ID=14819
order by MOTCONSU.DATE_CONSULTATION  desc

SELECT top 1 'Осложнение основного заболевания: '+cast(DIAGNOZ as varchar(max))+char(13)+char(10) as DIAGNOZ FROM  DATA_DIAGNOSIS data
join MOTCONSU on MOTCONSU.MOTCONSU_ID=DATA.MOTCONSU_ID 
WHERE MODELS_ID=658 and VID_ZABOLEVANIQ=1 and
MOTCONSU.MOTCONSU_EV_ID=14819
order by MOTCONSU.DATE_CONSULTATION  desc

SELECT top 1 case when DATALENGTH(DIAGNOZ)>0 then 'Сопутствующее заболевание: '+cast(DIAGNOZ as varchar(max)) else '' end as DIAGNOZ FROM  DATA_DIAGNOSIS data
join MOTCONSU on MOTCONSU.MOTCONSU_ID=DATA.MOTCONSU_ID 
WHERE MODELS_ID=658 and VID_ZABOLEVANIQ=2 and
MOTCONSU.MOTCONSU_EV_ID=14819
order by MOTCONSU.DATE_CONSULTATION  desc


