declare @FM_CLINK_ID int
set @FM_CLINK_ID = 14090
declare @FM_SERV_ID int
set @FM_SERV_ID = 1492

SELECT distinct
FM_PRICETYPE.FM_PRICETYPE_ID
,FM_PRICETYPE.LABEL
FROM
FM_CLINK FM_CLINK 
 LEFT OUTER JOIN FM_CLINK_PROG FM_CLINK_PROG ON FM_CLINK.FM_CLINK_ID = FM_CLINK_PROG.FM_CLINK_ID
 INNER JOIN FM_PROG_SERV FM_PROG_SERV ON (FM_CLINK.FM_CLINK_ID = FM_PROG_SERV.FM_CLINK_ID or FM_CLINK_PROG.FM_PROG_ID = FM_PROG_SERV.FM_PROG_ID)
 LEFT OUTER JOIN FM_PRICETYPE FM_PRICETYPE on FM_PROG_SERV.FM_PRICETYPE_ID = FM_PRICETYPE.FM_PRICETYPE_ID
WHERE
 (FM_CLINK.FM_CLINK_ID  = @FM_CLINK_ID and FM_PROG_SERV.FM_SERV_ID = @FM_SERV_ID)
 and isnull(FM_PROG_SERV.CANCEL,0)=0
 and isnull(FM_CLINK_PROG.CANCEL,0)= 0
 and isnull(FM_CLINK_PROG.CANCEL_AN,0) =0
 and FM_PRICETYPE.FM_PRICETYPE_ID is not null